### ISSUE TITLE
The live demo is not working

### ISSUE THREAD

**Issue by yuxiaomin** [ui-router/sample-app-ng2#1]
The live demo https://ui-router.github.io/sample-app-ng2/home
is not working. 
I cloned the source code and serve from local. It's working fine.

**Comment by christopherthielen** [comment]
thanks for letting me know!

**Comment by christopherthielen** [comment]
I fixed and republished the live demo.  Because we're using github pages, we have to use the hashbang now.


https://ui-router.github.io/sample-app-ng2/#/home
