### ISSUE TITLE
named views?

### ISSUE THREAD

**Issue by surfjedi** [ui-router/sample-app-ng2#3]
Can this do named views?

**Comment by christopherthielen** [comment]
It sure can.  There are a few examples of named views and how to target them.  

Here's one: https://github.com/ui-router/sample-app-ng2/blob/fa0d13b844fdcf209ab06f3be87e2f905742ded6/src/app/mymessages/mymessages.states.ts#L61-L67

And here is where the named ui-view is created: 
https://github.com/ui-router/sample-app-ng2/blob/fa0d13b844fdcf209ab06f3be87e2f905742ded6/src/app/mymessages/mymessages.component.ts#L18-L19
