### ISSUE TITLE
webpack: Failed to compile. (in a pure repo clone)

### ISSUE THREAD

**Issue by DrFairy** [ui-router/sample-app-ng2#4]
ERROR in /var/www/sample-app-ng2/src/app/app.module.ts (23,28): Argument of type '{ states: ({ name: string; redirectTo: string; component: typeof AppComponent; } | { parent: stri...' is not assignable to parameter of type 'RootModule'.
  Types of property 'config' are incompatible.
    Type '(router: UIRouter) => void' is not assignable to type '(uiRouterInstance: UIRouter, injector: Injector, module: StatesModule) => any'.
      Types of parameters 'router' and 'uiRouterInstance' are incompatible.
        Type 'UIRouter' is not assignable to type 'UIRouter'. Two different types with this name exist, but they are unrelated.
          Types of property 'locationService' are incompatible.
            Type 'LocationServices' is not assignable to type 'LocationServices'. Two different types with this name exist, but they are unrelated.
              Types of property 'dispose' are incompatible.
                Type '(router?: UIRouter) => any' is not assignable to type '(router?: UIRouter) => any'. Two different types with this name exist, but they are unrelated.
                  Types of parameters 'router' and 'router' are incompatible.
                    Type 'UIRouter' is not assignable to type 'UIRouter'. Two different types with this name exist, but they are unrelated.
                      Types of property 'locationService' are incompatible.
                        Type 'LocationServices' is not assignable to type 'LocationServices'. Two different types with this name exist, but they are unrelated.
                          Types of property 'dispose' are incompatible.
                            Type '(router?: UIRouter) => any' is not assignable to type '(router?: UIRouter) => any'. Two different types with this name exist, but they are unrelated.
                              Types of parameters 'router' and 'router' are incompatible.
                                Type 'UIRouter' is not assignable to type 'UIRouter'. Two different types with this name exist, but they are unrelated.

**Comment by nacmacfeegle** [comment]
Seeing this too
```$ npm -v
3.10.8

$ node -v
v6.9.0
```

**Comment by muscleman** [comment]
I cast routerFunc as <any> and it compiled

**Comment by muscleman** [comment]
I cast routerFunc as ANY and it compiled

**Comment by nacmacfeegle** [comment]
Did it run?

**Comment by muscleman** [comment]
i also had to extract the interfaces Message and Folder into separate ts files and fix where they were referenced.

but now i am getting a provider not found issue.


Gary


________________________________

**Comment by christopherthielen** [comment]
Bad things happen when npm installs two copies of `@uirouter/core`. (note: yarn handles this with no problems).  There was an explicit dependency on `@uirouter/core@^5.0.0` and a transitive dependency through `@uirouter/angular`.  npm seems to install one copy for each dependency.

I [removed the explicit dependency](https://github.com/ui-router/sample-app-ng2/commit/6827f108aa2d94a89a465108c2ab910ba03a7b0f) on `@uirouter/core` in package.json and npm is now only installing one copy.

**Comment by DaSchTour** [comment]
@christopherthielen It would help a lot if there was not hard fixed version for `@uirouter/core` in `@uirouter/angular` as this also leads to major problems when using JSPM.

**Comment by christopherthielen** [comment]
@DaSchTour `@uirouter/angular` _should_ have a hard dependency on `@uirouter/core` so a given version of `@uirouter/angular` always behaves the same way.

What problems does this cause for jspm?

**Comment by DaSchTour** [comment]
@christopherthielen the problem is, that there are different version installed. To have access to uirouter/core functions I have to install it explicitly with JSPM. But this leads to problems because uirouter/angular installs another version and so I have to instances of services and injection fails. So I have tell JSPM which version it should use for all dependencies after every update. Somehow the version and dependency handling of all uirouter modules (core, angular and rx) seams to be very inconsistent and IMHO a bit strange.

**Comment by christopherthielen** [comment]
> To have access to uirouter/core functions I have to install it explicitly with JSPM. 

This is surprising to me.  The `@uirouter/*` packages use what I think are typical node dependencies.  `core` has no external deps, `angular` depends on a specific version of `core` and `rx` has a peer dependency on a range of versions of `core.

**Comment by DaSchTour** [comment]
@christopherthielen that's definitely not true. `rx` for example has rollup as a runtime dependency. So instead of handling `core` as a dependency JSPM only offers rollup as a dependency.

**Comment by christopherthielen** [comment]
> rx for example has rollup as a runtime dependency. 

Ah yes, that's definitely wrong.  I see you filed a bug https://github.com/ui-router/rx/issues/5, thanks!

However, the legitimate `@uirouter/rx` dependencies are alrady listed as `peerDependencies`.  It looks like [JSPM supports peer deps](https://jspm.io/0.17-beta-guide/peer-dependencies.html).  Why doesn't this work? 
```
 "peerDependencies": {
    "@uirouter/core": ">=5.0.0",
    "rxjs": "^5.0.3"
  },
```

**Comment by DaSchTour** [comment]
@christopherthielen I really have no idea. But I have no time to test this as we changed our setup. As there are so many obstacles using `@angular/router` with JSPM I tried to to the migration from uirouter/angularjs to uirouter/angular on JSPM but now we've build up the project from scratch with angular-cli and try to minimize the dependency to 3rd party libraries.
